all:
	php cp.php make.md ../make.md
	php cp.php impl_tclass.md ../impl_tclass.md
	php cp.php overload2.md ../overload2.md
	php cp.php 'Implementing Haskell overloading.md' '../Implementing Haskell overloading.md'
	php cp.php poor_mans_type_classes_jp.md ../poor_mans_type_classes_jp.md
	php cp.php wadler_type_class.md ../wadler_type_class.md
